---

elasticsearch:
  hosts:
    el-instance:
      ansible_host: 34.231.171.181
      ansible_connection: ssh
      ansible_user: centos
kibana:
  hosts:
    k-instance:
      ansible_host: 34.268.113.192
      ansible_connection: ssh
      ansible_user: centos
filebeat:
  hosts:
    f-instance:
      ansible_host: 34.304.129.1171
      ansible_connection: ssh
      ansible_user: centos
